# Site settings

title: 软件镜像站
# title: 北京外国语大学开源软件镜像站
school: 
# school: 北京外国语大学
brand: Software Mirror
operator: --sora--
author: --sora--
desc: 本站由--sora--创建并运行维护。
# operator: 北外信息技术中心
logo: true
meow_404: true
issue_tag: sora-yyds
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirror.s-o-r-a.eu.org"
hostname: "mirror.s-o-r-a.eu.org"
urlv4: "https://mirrors4.tuna.tsinghua.edu.cn"
urlv6: "https://mirrors6.tuna.tsinghua.edu.cn"
aosp: "aosp.tuna.tsinghua.edu.cn"
arch_archive: "arch-archive.tuna.tsinghua.edu.cn"
pypi: "pypi.tuna.tsinghua.edu.cn"
homelink: "https://s-o-r-a.top/"
hide_navbar: false
hide_download: false
hide_server_status: false

hide_mirrorz: false
mirrorz_desc: --sora--のblog
mirrorz_link: "https://s-o-r-a.top/"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"

mirrorz_desc1: --sora--のcloud
mirrorz_link1: "https://cloud.s-o-r-a.top/"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"

mirrorz_desc2: --sora--の素材库
mirrorz_link2: "https://res.s-o-r-a.top/"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"

sponsors:
    megvii:
        name: "甲骨文股份有限公司"
        link: "https://www.oracle.com/"
        short: "甲骨文"
        eng: "Oracle"
        logo: "Oracle"
    huawei:
        name: "清华大学 TUNA 协会"
        link: "https://tuna.moe/"
        short: "TUNA协会"
        eng: "Tsinghua University Network Administrators"
        logo: "tuna-small"

sponsor:
  - megvii
  - huawei

poweredbys:
    Oracle: "ARM Neoverse N1 处理器"

poweredby: "Oracle"


# ==================================
# Build settings below, DO NOT TOUCH
# ==================================

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

vite:
    config_path: _src/vite.json
    viteConfig: _vite.config.mjs

plugins:
    - jekyll-relative-links
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

jekyll-minifier:
    exclude: [ 'assets/*' ]

exclude: [gen_robot.sh, geninfo/, gen_desc.py]
addition_exclude:
    - package.json
    - package-lock.json
    - node_modules/
    - Gemfile
    - Gemfile.lock
    - README.md
    - vendor/
    - Dockerfile*
    - LICENSE

# vim: ts=2 sts=2 sw=2 expandtab
